### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by IamSAB** [misibo/event-tool#1]
Security features

- [x] Registration
- [x] Login
- [x] Logout
- [x] Account confirmation
- [x] Email confirmation
- [x] Change password
- [x] Reset password
- [x] Authorization dependent on assigned user permission (check bit-wise as integer saved in column of user table, or with separate permission table)

**Comment by IamSAB** [comment]
I checked in the flask-security extension, how the email confirmation, password recovery works.

For password recovery:
- when requesting recovery [generate_reset_password_token](https://github.com/mattupstate/flask-security/blob/develop/flask_security/recoverable.py#L55) from user id and password_hash
- later check [reset_password_token_status](https://github.com/mattupstate/flask-security/blob/develop/flask_security/recoverable.py#L65) and get user and password with [get_token_status](https://github.com/mattupstate/flask-security/blob/develop/flask_security/utils.py#L407) with the [reset serizalizer](https://github.com/mattupstate/flask-security/blob/develop/flask_security/core.py#L331).
- Basically it is an implementation of URLSafeTimedSerializer from [itsdangerous](https://pythonhosted.org/itsdangerous/)

I think this approach is easier than creating an additional table for pending users and store a token for each use case in the database. What do you think?

**Comment by IamSAB** [comment]
I propose each user has a status. It is either

- pending
- activated
- or blocked

The ORM supports Enum field types.

**Comment by goldminer77** [comment]
Du hast Recht, itsdangereous ist für die Account-Aktivierung eine gute Idee, sollte eine kleine Änderung sein. Dann benötigt man die doofe PendingUser-Tabelle nicht. Ich glaube für Passwort-Resets ist die jetztige Lösung mit den Tokens in Ordnung, weil man keine Extra-Tabelle benötigt.

Wegen den Status Flags, ich will diese vermeiden, soweit es geht. Ich will eigentlich davon ausgehen können, dass alle Benutzer in der User-Tabelle gültig sind.

Was ist der Zweck des blocked-Status? Spam? Ich würde einfach den User löschen und die E-Mail Adresse auf eine schwarze Liste tun.

**Comment by IamSAB** [comment]
Ja, für ungebetene Benutzer - zudem verhindern blockierte Benutzer automatisch, dass sich weiter mit dieser Email registrieren (also auch eine Art schwarze Liste ohne zusätzliche checks)

Ich würde alle Benutzer in einer Tabelle hinterlegen, da man dan alle Benutzer mit einer Abrfrage auflisten, filtern und sortieren kann. Hat der Benutzer einen Status, kann man ihn einfach ändern, ohne Benutzer zwischen Tabellen hin und her zu schieben. Zudem kann man sehr flexibel weitere Status hinzufügen.
Will man nur die aktiven Benutzer, kann man einfach eine function im Model hinzufügen z.b get_active_users als shortcut.

**Comment by goldminer77** [comment]
Im aktuellen Design ist die Email nicht Unique in unserer Datenbank, das heisst, ungebetene Benutzer können sich einfach mit einem anderen Namen (aber selben E-Mail) anmelden, wenn wir sie blocken.
Ausser wir fügen bei der Registrierung einen zusätzlichen Check ein, der prüft ob diese E-Mail Adresse irgenwo geblockt ist.

**Comment by IamSAB** [comment]
Stimmt, ich würde einen zuätzlichen check machen, oder besser die abfrage anpassen:

`username=form.username.data OR (email=form.email.data AND status='blocked')`
