### ISSUE TITLE
Use UTC timezone internally

### ISSUE THREAD

**Issue by goldminer77** [misibo/event-tool#13]
Ich würde in der Datenbank alle Daten in der UTC Zeitzone abspeichern. Damit vermeiden wir Probleme, falls unser Hosting Provider in einer anderen Zeitzone läuft (datetime.now() wäre dann inkorrekt).

Library: https://pypi.org/project/pytz/
Unsere Zeitzone ist Europe/Zurich. 
Für die aktuelle Zeit datetime.utcnow() verwenden, anstatt datetime.now().

**Comment by IamSAB** [comment]
Ja, wieso nicht. Ist robuster und bringt nicht viele Änderungen mit sich. Das ORM speichert es glaube ich sowieso im UTC format.

**Comment by goldminer77** [comment]
> Das ORM speichert es glaube ich sowieso im UTC format.

Das ist nicht der Fall, datetimes im ORM sind standardmässig "naive" (Siehe: https://docs.sqlalchemy.org/en/13/core/type_basics.html), was Sinn macht, weil die meisten Datenbanken sowieso keine Zeitzonen unterstützen.

**Comment by goldminer77** [comment]
```
import pytz
from datetime import datetime

mytz = pytz.timezone('Europe/Zurich')


def utc_to_localtime(date):
    return pytz.utc.localize(date).astimezone(mytz).replace(tzinfo=None)


def localtime_to_utc(date):
    return mytz.localize(date).astimezone(pytz.utc).replace(tzinfo=None)
```

**Comment by IamSAB** [comment]
Müsste man dann nicht auch in der DB Zeitzonen unterstützen bzw. erlauben?

**Comment by goldminer77** [comment]
Nicht unbedingt. Du kannst es auch mit der Konvention machen, dass alle Zeiten in der Datenbank sind konsistent UTC sind und die Zeitzonen-Konvertierung jeweils in Python machen. Zwar haben Datenbanken in der Regel einen Datentyp für Zeiten mit Offset-Information. Das Problem mit diesem Datentyp ist aber, dass er nicht portabel ist, weil die Semantics auf jeder Datenbank anders sind. Deshalb ist es in der Regel besser, alles in UTC ohne Offset-Information zu speichern und die Konvertierung in der Applikation zu machen.
Der Grund, weshalb man Zeiten in UTC abspeichert und nicht in Lokal-Zeit, ist dass Lokal-Zeit nicht eindeutig ist während Sommerzeit-Winterzeit-Wechsel.

**Comment by IamSAB** [comment]
Somit speicher wir immer die "Nullzeit" in der DB und rechnen in python noch die zeitverschiebung hinzu. Dann müssen wir aber immer die Zeitzone des Clients wissen. (In unserem Fall ist das ja bekannt, also +1).
Ich habe noch etwas gefunden, https://github.com/spoqa/sqlalchemy-utc, was die Zeit immer in UTC speichern würde.

**Comment by goldminer77** [comment]
Siehe PR: https://github.com/misibo/event-tool/pull/15

**Comment by goldminer77** [comment]
Ich habe eine Klasse LocalDateTimeField(extends DateTimeField) in forms.py eingeführt die UTC als Lokalzeit anzeigt. Ausserdem habe ich in models.py einen neuen Datentyp UtcDateTime definiert, der alles zu UTC konvertiert und speichert. Ausserdem wirft UtcDateTime eine Exception, falls man versucht, eine Zeit ohne Zeitzonenangabe zu speichern.
