### ISSUE TITLE
UIKit Icons funktionieren nicht

### ISSUE THREAD

**Issue by goldminer77** [misibo/event-tool#16]
Was muss ich machen, damit die UIkit Icons korrekt angezeigt werden?

1. Die Icon-Buttons (z.B class="uk-icon-button uk-icon-pencil") werden nicht angezeigt: https://getuikit.com/v2/docs/icon.html
2. Viele Icons werden nicht angezeigt, wie zum Beispiel uk-icon="thumps-up", obwohl sie gemäss font-awesome-Webseite frei verfügbar sind sind.

**Comment by IamSAB** [comment]
Du hast die Docs für v2 statt v3. Die neue Version benützt nicht font awesome und hat eigene (weniger) icons.
https://getuikit.com/docs/icon
