### ISSUE TITLE
Merge feature branch

### ISSUE THREAD

**Issue by IamSAB** [misibo/event-tool#18]
Kannst du checken, ob mit dem develop branch noch alles von dir geht? Ich musst ziemlich viele conflicts resolve beim mergen von feature/paginate-filter-sort.

Du hast ja jetz pull request gemacht, ist das besser von der übersicht her? Ich check jedoch nicht so genau, wie die funktionieren ...

**Comment by IamSAB** [comment]
Beachte, dass ab jetzt flask-sqlalchemy benützt wird #12

**Comment by goldminer77** [comment]
Ich habe meine Änderungen in die Feature Branch gemergt. Dein commit "Add dashboard, draft event, group view & user crud" hat alle Referenzen nach url_for("user.edit") kaputt gemacht, kannst du diese noch fixen, so schnell wie möglich, damit ich weiterarbeiten kann?

**Comment by IamSAB** [comment]
cd3b0dec66bb337e7aa571784568f53ad2b74ba6

**Comment by IamSAB** [comment]
in vscode ganz einfach ctrl-shift-f: search and replace in all files ;D

**Comment by goldminer77** [comment]
Danke!

**Comment by goldminer77** [comment]
Wir haben zuviel Merge-Errors. Ich glaube die können wir vermindern, wenn wir folgende Regeln beachten:
- Einrückungen beibehalten.
- Reihenfolge der Zeilen möglichst nicht ändern.
- Imports sind ein grosses Problem, da haben wir immer Merge-Konflikte. Vielleicht sollten wir doch lieber nur das Modul importieren anstatt die einzelnen Klassen, also `from .forms import forms` anstatt `from .forms import UserEditForm, EventEditForm, etc.`
- Keine Auto-Formatter-Tools verwenden, diese verändern das ganze Layout und dann haben wir Merge-Konflikte. Wenn wir ein Tool verwenden wollen, müssen wir beide dasselbe Tool verwenden.

**Comment by IamSAB** [comment]
Stimmt, diese Konflikte sind echt mühsam. 

Ich benutze denselber formatter wie du (vom settings file). die imports kann man mit vscode formatieren: ctrl-shift-p und dann refactor: sort imports

**Comment by goldminer77** [comment]
Ich verwende jetzt PyCharm, VSCode ist buggy auf Fedora.

**Comment by goldminer77** [comment]
Das Problem mit den Imports ist, dass wenn ich Klasse A hinzufüge und du Klasse B hinzufügts, dann haben wir einen Merge-Konflikt. Ich glaube das ist ein Grund weshalb Modul-Imports statt Klassen-Imports empfohlen werden.

Ich glaube, PR machen bei grösseren Änderungen/Features Sinn, wenn du 1-2 Tage warten kannst, bis der PR "Approved" ist.. Bei Bug-Fixes und kleineren Sachen würde ich normal pushen.

**Comment by goldminer77** [comment]
Ich habe den Auto-Formatter in PyCharm getestet. So wie das aussieht, funktioniert der ähnlich wie derjenige im VSCode. Das heisst es ist OK, wenn du "Sort Imports" und "Format document" verwendest.
