### ISSUE TITLE
URL naming convention

### ISSUE THREAD

**Issue by goldminer77** [misibo/event-tool#21]
Welche Konvention für URL's sollen wir benutzen?

Ich kenne halt RESTful: https://medium.com/the-andela-way/rest-api-how-to-bce359ad7362

List Events: GET /events
Filter/Sort Events: GET /events?sort=name,group=20up
Create Event: POST /events
Update Event: PUT /events/id
Delete Event: DELETE /events/id

Ist halt eher für Backends. Ich weiss nicht, ob man das bei Frontends so machen kann.

**Comment by IamSAB** [comment]
Wollte ich auch so machen, das funktioniert aber nur mit Ajax bzw. XMLHttpRequest, da HTML forms nur GET oder POST erlauben.

**Comment by IamSAB** [comment]
Ich habe nur für create oder edit ein POST, da einzig dort, daten gesendet werden. löschen tu ich mit GET, da ich ja nur die id brauche. GET hat auch den vorteil, dass ich keine form zu senden brauche, da jeder GET request auch mit einer URL erzeugt werden kann bzw. GET = URL

**Comment by goldminer77** [comment]
> Wollte ich auch so machen, das funktioniert aber nur mit Ajax bzw. XMLHttpRequest, da HTML forms nur GET oder POST erlauben.

Ja, das habe ich vermutet.

Dann machen wir das also folgendermassen?

List Events: GET /events
Filter/Sort Events: GET /events?sort=name,group=20up
Create Event: GET&POST /events/create
Update Event: GET&POST /events/id
Delete Event: GET /events/delete/id

**Comment by IamSAB** [comment]
Momentan habe ich es so: 

List Events: GET /event
View Event (public): GET /event/view/<id>
Filter/Sort Events: GET /event?sort=name,group=20up
Create Event: GET&POST /event/create
Update Event: GET&POST /event/edit/<id>
Delete Event: GET /event/delete/<id>
