### ISSUE TITLE
Track changes to user, groups and events relationships, and send subsequent invitations if necessary.

### ISSUE THREAD

**Issue by goldminer77** [misibo/event-tool#8]
- [ ] Send follow-up invitation if user joined a group which was assigned to an event

- [ ] Send follow-up invitations if a group was added to an event.

- [ ] Note: An invitation email is never sent twice to the same user.

- [ ] Note: An invitation that was sent is permanent, even if groups are removed from an event or a user unsubscribed from a group.

**Comment by IamSAB** [comment]
There should also be a notification whenever an event is changed (or some attributes).

The SQLAlchemy ORM offers an easy way to track attributes changes or table manipulation via events: https://docs.sqlalchemy.org/en/13/orm/events.html

**Comment by goldminer77** [comment]
Das Event-System ist ziemlich kompliziert und hat Limitierungen. Es ist zum Beispiel nicht ohne weiteres möglich, im Event-Handler neue Records zu erzeugen (z.B für Einladungen). Es ist vielleicht einfacher, die Callbacks für die Einladungen manuell aufzurufen.

**Comment by IamSAB** [comment]
Einladungen werden auf Befehl eines Mangers oder Admins für einen spezifischen Event versendet. Dies wird mit der `invited` spalte in der Event table markiert. Jedesmal wenn ein Benutzer eine Gruppe betritt, wird überprüft, für welche Events eine Einladungen nachversendet werden soll.
