### ISSUE TITLE
Let invitees accept/reject an invitation

### ISSUE THREAD

**Issue by goldminer77** [misibo/event-tool#9]
- [x] An invitation mail contains a link which lets the user modify the content of an invitation form. No user authentication is needed, the link is enough.

- [x] The user can accept or reject the invitation until the deadline.

- [x] The user can specify the number of additional seats in his car if he is a driver at any time.

- [x] The user can invite (unregistered) friends until the deadline.

**Comment by IamSAB** [comment]
Easiest way would be to generate tokens from given user and action related data with the [itsdangerous](https://pythonhosted.org/itsdangerous/) extensions.

**Comment by goldminer77** [comment]
Itsdangereous ist eigentlich nur für Kurzzeit-Daten wie Session-Tokens und Passwort-Reset-Links gedacht. Itsdangereous benötigt einen Secret-Key, der irgendwo gespeichert werden muss, wenn die generierten Tokens einen Neustart des Servers gültig bleiben sollen Das heisst, für Einladungen, die für längere Zeit bestehen müssen, bietet itsdangereous keinen Vorteil gegenüber Tokens die in der Datenbank gespeichert werden. Im Gegenteil, wenn du den Secret-Key änderst, werden alle existierenden Einladungen ungültig.

**Comment by IamSAB** [comment]
Stimmt, man darf den secret key nicht ändern. Wenn wir aber den Token von dem primary key der invitation generieren, verfällt nur der token bzw. der link welcher mit dem Mail versandt wurde. Grundsätzlich ist ja der Token unendlich lange gültig, aussert man generiert ihn mit einem Ablaufdatum. Der Hauptvorteil für mich ist, dass man direkt vom Token den User und die Invitation lesen kann und nicht extra noch in der Datenbank etwas hinterlegen oder suchen muss.

**Comment by goldminer77** [comment]
Du meinst secret key = primary key of invitation? Das geht nicht. Der Secret-Key muss unvorhersagbar sein, also mit einem kryptographisch sicherem Zufallszahlengenerator generiert werden (z.B mit os.urandom), du kannst dafür nicht die primary keys verwenden, weil die  typischerweise fortlaufend sind und damit vorhersagbar. Ausserdem, beim Validieren des Token (z.B wenn der User den Link öffnet), wie weisst du, wessen primary key du verwenden muss? Du müsstest jeden primary key in der DB ausprobieren, bis du den passenden gefunden hasst. Bedenke, du darst den primary key nicht mit der E-mail mitschicken, weil der secret key geheim bleiben muss.

**Comment by IamSAB** [comment]
Wir benutzen den secret-key unserer app, und generieren mit dem primary key und einem [salt](https://pythonhosted.org/itsdangerous/#the-salt) mit dem serializer einen token.
Wie gesagt, ist der secret key fest definiert, am besten im instance/config.py file natürlich.
Der serializer kann den token generieren, aber auch verschlüsselte daten (mithilfe dem secret-key und dem salt) wieder herauslesen.

**Comment by goldminer77** [comment]
Ich arbeite gerade an den Einladungen. Ich mache es jetzt mit einem Token, das in der Invitations-Tabelle gespeichert wird, ich finde das einfacher. Wir benötigen die Invitations-Tabelle sowieso, d.h itsdangereous bringt hier keinen wirklichen Vorteil. Ich schicke im Invitation-Link zusätzlich zum Token die Invitation-ID mit, damit man in der Datenbank nicht das Token suchen muss.
